[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.32"
log = "0.4"
nalgebra = "0.34.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
web-sys = "0.3.78"
